cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('',views.index,name='cart_index'),
    path('addCart/<int:product_id>/',views.add_to_cart,name='add_cart'),
    path('delete/<int:product_id>/',views.delete_item,name='cart_item_delete'),
    path('addCount/<int:product_id>/',views.add_count,name='add_count'),
    path('reduceCount/<int:product_id>/',views.reduce_count,name='reduce_count')
]

chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('new/<int:plastic_id>/',views.new_conversation,name='new'),
    path('inbox/',views.inbox,name='inbox')
]

rekart/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path('',include('core.urls')),
    path('shop/',include('shop.urls')),
    path('accounts/',include('accounts.urls')),
    path('cart/',include('cart.urls')),
    path('chat/',include('chat.urls')),
    path("__debug__/", include("debug_toolbar.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views


app_name = 'shop'

urlpatterns = [
    path('',views.shop,name='shop'),
    path('addItem/',views.add_item,name='add_item'),
    path('product_details/<slug:slug>/',views.product_view,name='product_details'),
    path('plastic_details/<slug:slug>/',views.plastic_view,name='plastic_details'),
    path('delete_product/<int:product_id>/',views.delete_product,name='delete_product'),
    path('delete_plastic/<int:plastic_id>/',views.delete_plastic,name='delete_plastic'),
    path('update_product/<int:product_id>/',views.update_product,name='update_product'),
    path('update_plastic/<int:plastic_id>/',views.update_plastic,name='update_plastic')
]

cart/models.py
from django.db import models
from accounts.models import Customer
from core.models import Products
# Create your models here.

class CartList(models.Model):
    user = models.OneToOneField(Customer,on_delete=models.CASCADE,related_name='cart')
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.user.username}'s cart"


class Items(models.Model):
    product = models.ForeignKey(Products,on_delete=models.CASCADE)
    cart = models.ForeignKey(CartList,on_delete=models.CASCADE,related_name='items')
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.product.name

shop/models.py
from django.db import models
from django.contrib.auth.models import User

class Employee(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    department = models.CharField(max_length=30)

shop/forms.py
from django.forms import ModelForm
from django import forms

from accounts.models import Customer

from core.models import Products
from core.models import ProductCategory
from core.models import PlasticWaste
from core.models import Category

choice = PlasticWaste.UnitChoices


CLASS_INPUT = 'block w-full rounded-md border-0 p-3 mb-4 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-500 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-primary sm:text-sm sm:leading-6'

class ProductsForm(ModelForm):
    class Meta:
        model = Products
        fields = ['name','description','stock','price','image','category']

    name = forms.CharField(label='Name',widget=forms.TextInput(attrs={
        'name' : 'name',
        'class' : CLASS_INPUT
    }))

    description = forms.CharField(widget=forms.Textarea(attrs={
        'name' : 'description',
        'class' : CLASS_INPUT
    }))

    stock = forms.IntegerField(widget=forms.NumberInput(attrs={
        'name' : 'stock',
        'class' : CLASS_INPUT
    }))

    price = forms.DecimalField(widget=forms.NumberInput(attrs={
        'name' : 'price',
        'class' : CLASS_INPUT
    }))

    image = forms.ImageField(widget=forms.ClearableFileInput(attrs={
        'name' : 'image',
        'class' : CLASS_INPUT
    }))

    category = forms.ModelChoiceField(queryset=ProductCategory.objects.all(),widget=forms.Select(attrs={
        'name' : 'category',
        'class' : CLASS_INPUT
    }))


class PlasticWasteForm(ModelForm):
    class Meta:
        model = PlasticWaste
        fields = ['name','description','quantity','unit','price','category','image']
    
    name = forms.CharField(label='Name',widget=forms.TextInput(attrs={
        'name' : 'name',
        'class' : CLASS_INPUT
    }))

    description = forms.CharField(widget=forms.Textarea(attrs={
        'name' : 'description',
        'class' : CLASS_INPUT
    }))

    quantity = forms.IntegerField(widget=forms.NumberInput(attrs={
        'name' : 'quantity',
        'class' : CLASS_INPUT
    }))

    unit = forms.ChoiceField(choices=choice.choices,widget=forms.Select(attrs={
        'name' : 'unit',
        'class': CLASS_INPUT
    }))

    price = forms.DecimalField(widget=forms.NumberInput(attrs={
        'name' : 'price',
        'class' : CLASS_INPUT
    }))

    category = forms.ModelChoiceField(queryset=Category.objects.all(),widget=forms.Select(attrs={
        'name' : 'category',
        'class' : CLASS_INPUT
    }))

    image = forms.ImageField(widget=forms.ClearableFileInput(attrs={
        'name' : 'image',
        'class' : CLASS_INPUT
    }))

cart/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.http import JsonResponse
from . models import CartList
from . models import Items
from accounts.models import Customer
from core.models import Products


SHIPPING_CHARGE = 40

@login_required(login_url='/accounts/login')
def index(request):
    cart_items = None
    cart = None
    try:
        customer = Customer.objects.get(user = request.user)
        cart = CartList.objects.get(user = customer)
        cart_items = Items.objects.filter(cart = cart)

        sub_total = 0

        for item in cart_items:
            sub_total += item.product.price * item.quantity
        
        total = sub_total + SHIPPING_CHARGE

    except:
        pass

    context = {
        'cart_items' : cart_items,
        'sub_total' : sub_total,
        'total' : total,
        'shipping_charge' : SHIPPING_CHARGE
    }

    return render(request,'cart.html',context)

@login_required(login_url='/accounts/login')
def add_to_cart(request,product_id):
    product = Products.objects.get(id = product_id)
    customer = Customer.objects.get(user = request.user)
    try:
        cart = CartList.objects.get(user = customer)
    except CartList.DoesNotExist:
        cart = CartList.objects.create(user = customer)
        cart.save()
    
    try:
        cart_item = Items.objects.get(product = product,cart = cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except Items.DoesNotExist:
        cart_item = Items.objects.create(
            product = product,
            quantity = 1,
            cart = cart
        )
        cart_item.save()
    return redirect('cart:cart_index')

def add_count(request,product_id):
    product = Products.objects.get(id = product_id)
    customer = Customer.objects.get(user = request.user)
    cart = CartList.objects.get(user=customer)
    cart_item = Items.objects.get(product = product,cart = cart)
    quantity = cart_item.quantity
    if quantity < product.stock:
        cart_item.quantity += 1
        quantity = cart_item.quantity
        cart_item.save()
        response = JsonResponse({
            'quantity':quantity,
            'price' : product.price
        })
    else:
        response = JsonResponse({'quantity':'error'})
    return response

def reduce_count(request,product_id):
    product = Products.objects.get(id = product_id)
    customer = Customer.objects.get(user = request.user)
    cart = CartList.objects.get(user = customer)
    cart_item = Items.objects.get(product = product,cart = cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
        return JsonResponse({
            'quantity' : cart_item.quantity,
            'price': product.price,
        })
    else:
        cart_item.delete()
        return JsonResponse({'quantity' : 'empty'})
    

def delete_item(request,product_id):
    product = Products.objects.get(id=product_id)
    customer = Customer.objects.get(user=request.user)
    cart = CartList.objects.get(user=customer)
    cart_item = Items.objects.get(product = product,cart=cart)
    cart_item.delete()
    return redirect('cart:cart_index')
     

shop/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from itertools import chain
from django.contrib.auth.models import User
from django.utils.text import slugify

from core.models import Category
from core.models import ProductCategory
from core.models import Products
from core.models import PlasticWaste

from . forms import ProductsForm
from . forms import PlasticWasteForm



def shop(request):
    plastic_category = Category.objects.values_list('short_name',flat=True)
    product_category = ProductCategory.objects.values_list('name',flat=True)
    categories = list(chain(plastic_category,product_category))


    category = request.GET.get('category',0)

    products = None
    plastic_waste = None

    
    if category:
        if category == 'P':
            products = Products.objects.all()
        elif category == 'W':
            plastic_waste = PlasticWaste.objects.all()
        else:
            products = Products.objects.filter(category__name=category)
            plastic_waste = PlasticWaste.objects.filter(category__short_name=category)

    else:
        products = Products.objects.all()
        plastic_waste = PlasticWaste.objects.all()

    context = {
        'categories':categories,
        'products':products,
        'plastic_waste':plastic_waste,
        'category_name':category
    }

    return render(request,'shop.html',context)



def product_view(request,slug):
    product = Products.objects.get(slug = slug)

    context = {
        'product' : product,
        'item' : 'product'
    }
    return render(request,'product_detail.html',context)

def plastic_view(request,slug):
    plastic = PlasticWaste.objects.get(slug = slug)
    context = {
        'plastic' : plastic,
        'item' : 'plastic'
    }
    return render(request,'plastic_details.html',context)

def add_item(request):
    type = request.GET.get('type',None)

    if request.method == 'POST':
        if type == 'product':
            form = ProductsForm(request.POST,request.FILES)
        else:
            form = PlasticWasteForm(request.POST,request.FILES)
        if form.is_valid():
            user = User.objects.get(username=request.user)
            obj =  form.save(commit=False)
            obj.seller = user
            obj.slug = slugify(obj.name)
            obj.save() 
        return redirect('/')
    else:
        if type == 'product':
            form = ProductsForm()
        else:
            form = PlasticWasteForm()

    context = {'form':form,'type' : type}

    return render(request,'new.html',context)

def update_product(request,product_id):
    product = Products.objects.get(id = product_id)
    if request.method == 'POST':
        form = ProductsForm(request.POST,request.FILES,instance=product)
        if form.is_valid:
            obj = form.save(commit=False)
            obj.slug = slugify(obj.name)
            obj.save()
            return redirect('shop:product_details',slug = product.slug)
    else:
        form = ProductsForm(instance=product)
    return render(request,'new.html',{'form':form,'type' : 'product','update':True})


def update_plastic(request,plastic_id):
    plastic = PlasticWaste.objects.get(id = plastic_id)
    if request.method == 'POST':
        form = PlasticWasteForm(request.POST,request.FILES,instance=plastic)
        if form.is_valid:
            form.save()
            return redirect('shop:plastic_details',slug = plastic.slug)
    else:
        form = PlasticWasteForm(instance=plastic)
    return render(request,'new.html',{'form':form,'type' : 'plastic','update' : True})


def delete_product(request,product_id):
    product = Products.objects.get(id = product_id)
    product.delete()
    return redirect('shop:shop')

def delete_plastic(request,plastic_id):
    plastic = PlasticWaste.objects.get(id = plastic_id)
    plastic.delete()
    return redirect('shop:shop')

templates/base.html
{% load static %}
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en" class="scroll-smooth">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rekart</title>
    {% tailwind_css %}
</head>
<body class="font-body">
    
    <div>   <!-- content-wrapper -->
        <header>
            <nav class="flex justify-between items-center p-5 border-b-2 border-gray-200">
                <div>
                    <h1>
                        <a href="/" class="font-bold text-primary text-2xl uppercase">Rekart</a>
                    </h1>
                </div>

                <div class="hidden md:block">
                    <ul class="flex gap-5 font-semibold black-text">
                        <li>
                            <a href="/" class="hover:font-bold">Home</a>
                        </li>
                        <li>
                            <a href="{% url 'shop:shop' %}" class="hover:font-bold">Shop</a>
                        </li>
                        <li>
                            <a href="#" class="hover:font-bold upp">Dashboard</a>
                        </li>
                        <li>
                            <a href="{% url 'cart:cart_index' %}" class="hover:font-bold upp">Cart</a>
                        </li>
                    </ul>
                </div>
                
                <ul class="hidden md:flex gap-2">

                    {% if user.is_authenticated %}
                        {% if user.customer.is_seller %}
                            <div class="mr-2 relative inline-flex w-fit">
                                <a href="{% url 'chat:inbox' %}">
                                    <div class="absolute bottom-auto left-auto right-0 top-0 z-10 inline-block -translate-y-1/2 translate-x-2/4 rotate-0 skew-x-0 skew-y-0 scale-x-100 scale-y-100 rounded-full bg-red-600 p-2.5 text-xs">

                                    </div>
                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                        <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 13.5h3.86a2.25 2.25 0 012.012 1.244l.256.512a2.25 2.25 0 002.013 1.244h3.218a2.25 2.25 0 002.013-1.244l.256-.512a2.25 2.25 0 012.013-1.244h3.859m-19.5.338V18a2.25 2.25 0 002.25 2.25h15A2.25 2.25 0 0021.75 18v-4.162c0-.224-.034-.447-.1-.661L19.24 5.338a2.25 2.25 0 00-2.15-1.588H6.911a2.25 2.25 0 00-2.15 1.588L2.35 13.177a2.25 2.25 0 00-.1.661z" />
                                    </svg>
                                </a>  
                            </div>
                            <li>
                                <a href="#" onclick="openPopup()" class="btn text-xs btn-color hover-effect">Add item</a>
                            </li>
                        {% endif %}
                        <li>
                            <a href="{% url 'logout' %}" class="btn text-xs btn-color hover-effect">Logout</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url 'signup' %}" class="btn text-xs btn-color hover-effect">Sign up</a>
                        </li>
                        <li>
                            <a href="{% url 'login' %}" class="btn text-xs btn-color hover-effect">Login</a>
                        </li>
                    {% endif %}
                </ul>

                <div class="px-4 cursor-pointer md:hidden" id="burger">
                    <svg class="w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
                    </svg>  
                </div>

            </nav>

            <ul class="border-t-2 border-gray-300 text-lg text-center font-semibold black-text hidden md:hidden" id="phone-menu">
                {% if user.is_authenticated %}
                <li class="py-4">
                    <a href="{% url 'logout' %}" class="hover:font-bold">Logout</a>
                </li>
                <li class="py-4">
                    <a href="#" onclick="openPopup()" class="hover:font-bold">Add item</a>
                </li>
                {% else %}
                <li class="py-4">
                    <a href="{% url 'login' %}" class="hover:font-bold">Login</a>
                </li>
                <li class="py-4">
                    <a href="{% url 'signup' %}" class="hover:font-bold">Sign up</a>
                </li>
                {% endif %}
                <li class="py-4">
                    <a href="/" class="hover:font-bold">Home</a>
                </li>
                <li class="py-4">
                    <a href="shop.html" class="hover:font-bold">Shop</a>
                </li>
                <li class="py-4">
                    <a href="#" class="hover:font-bold upp">Dashboard</a>
                </li>
                <li class="py-4">
                    <a href="{% url 'cart:cart_index' %}" class="hover:font-bold upp">Cart</a>
                </li>
            </ul>
        </header>
        <div id="popup" class="popup">
            <div class="flex justify-end mr-2">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 font-extrabold cursor-pointer hover:text-red-700" onclick="closePopup()">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                </svg>     
            </div>
            <p class="text-center mb-6">What would you like to add..?</p>
            <div class="flex justify-center flex-wrap align-middle gap-8">
                <a href="{% url 'shop:add_item' %}?type=product" class="px-4 py-2 bg-primary text-white rounded-md font-bold hover:bg-secondary">Recycled product</a>
                <a href="{% url 'shop:add_item' %}?type=plastic" class="px-4 py-2 bg-primary text-white rounded-md font-bold hover:bg-secondary">Plastic waste</a>
            </div>
        </div>
        {% block content %}

        {% endblock %}
    </div>
    <footer class="h-32 bg-gray-900 flex items-center justify-center text-gray-300 text-xs">
            <p>
                &#169; GROUP 7 CSA MEC
            </p>
    </footer>
    <script src="{% static 'script/popup.js' %}" ></script>
    <script src="{% static 'script/script.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% load static tailwind_tags %}
{% block content %}
<div class="sm:h-screen bg-gray-100 pt-20 pb-10">
    <h1 class="mb-10 text-center text-2xl font-bold">Cart Items</h1>
    <div class="mx-auto max-w-5xl justify-center px-6 md:flex md:space-x-6 xl:px-0">
        <div class="rounded-lg md:w-2/3">
            {% for i in  cart_items %}
            <div class="justify-between mb-6 rounded-lg bg-white p-6 shadow-md sm:flex sm:justify-start parent">
                <img src="{{i.product.image.url}}"
                    alt="product-image" class="w-full rounded-lg sm:w-40" />
                <div class="sm:ml-4 sm:flex sm:w-full sm:justify-between items-center">
                    <div class="mt-5 sm:mt-0">
                        <a href="{% url 'shop:product_details' i.product.slug %}">
                            <h2 class="text-lg font-bold text-gray-900">{{i.product.name}}</h2>
                        </a>
                        <!-- <p class="mt-1 text-xs text-gray-700">36EU - 4US</p> -->
                    </div>
                    <div class="mt-4 flex justify-between im sm:space-y-6 sm:mt-0 sm:block sm:space-x-6">
                        <div class="flex items-center border-gray-100">
                            <span
                                onclick="quantityChange({{i.product.id}},0,event)"
                                class="cursor-pointer rounded-l font-bold bg-gray-100 py-1 px-3.5 duration-100 hover:bg-primary hover:text-blue-50">
                                - 
                            </span>
                            
                            <div class="px-3" id="item_quantity">
                                {{i.quantity}}
                            </div>

                            <span
                                onclick="quantityChange({{i.product.id}},1,event)"
                                class="cursor-pointer rounded-r font-bold bg-gray-100 py-1 px-3 duration-100 hover:bg-primary hover:text-blue-50">
                                + 
                            </span>
                        </div>
                        <div class="flex items-center space-x-4">
                            <p class="text-sm">&#8377 {{i.product.price}}</p>
                            <a href="{% url 'cart:cart_item_delete' i.product.id %}">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                                    stroke="currentColor" class="h-5 w-5 cursor-pointer duration-150 hover:text-red-500">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                                </svg>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <!-- Sub total -->
        <div class="mt-6 h-full rounded-lg border bg-white p-6 shadow-md md:mt-0 md:w-1/3">
            <div class="mb-2 flex justify-between">
                <p class="text-gray-700">Subtotal</p>
                <p class="text-gray-700">&#8377
                    <span id="sub-total">
                        {{sub_total}}
                    </span>
                </p>
            </div>
            <div class="flex justify-between">
                <p class="text-gray-700">Shipping</p>
                <p class="text-gray-700">&#8377 {{shipping_charge}}</p>
            </div>
            <hr class="my-4" />
            <div class="flex justify-between">
                <p class="text-lg font-bold">Total</p>
                <div class="">
                    <p class="mb-1 text-lg font-bold">&#8377
                        <span id="total">
                            {{total}}
                        </span>
                    </p>
                </div>
            </div>
            <button class="mt-6 w-full rounded-md bg-secondary py-1.5 font-medium text-blue-50 hover:bg-primary">Checkout</button>
        </div>
    </div>
</div>
<script src="{% static 'script/cart.js' %}"></script>
{% endblock %}

templates/login.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en" class="h-full bg-white">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    {% tailwind_css %}
</head>
<body class="h-full font-body" >
    <div class="flex min-h-full flex-col justify-center px-6 py-12 lg:px-8">
        <div class="sm:mx-auto sm:w-full sm:max-w-sm">
            <h2 class="mt-10 text-center text-2xl font-bold leading-9 tracking-tight text-gray-900">Sign in to your account</h2>
        </div>
    
        <div class="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">
            <form class="space-y-6" method="POST">
                {% csrf_token %}
                <div>
                    <label for="username" class="block text-sm font-medium leading-6 text-gray-900">Username</label>
                    <div class="mt-2">
                        {{form.username}}
                    </div>
                </div>
        
                <div>
                    <div class="flex items-center justify-between">
                        <label for="password" class="block text-sm font-medium leading-6 text-gray-900">Password</label>
                        <div class="text-sm">
                            <a href="#" class="font-semibold text-primary hover:text-secondary">Forgot password?</a>
                        </div>
                    </div>
                    <div class="mt-2">
                        {{form.password}}
                    </div>
                </div>

                {% if form.errors or form.non_field_errors %}
                    <div class="mb-3 p-6 text-red-700 font-bold text-center">
                        Wrong username or password!!
                    </div>
                {% endif %}
                <div>
                <button type="submit" class="flex w-full justify-center rounded-md bg-primary px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-secondary focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary">Login</button>
                </div>
            </form>
    
            <p class="mt-10 text-center text-sm text-gray-500">
                Not a user?
                <a href="{% url 'signup' %}" class="font-semibold leading-6 text-primary hover:text-secondary">Sign Up</a>
            </p>
        </div>
    </div>
</body>
</html>

templates/plastic_details.html
{% extends 'base.html' %}
{% load static %}
{% load static tailwind_tags %}
{% block content %}
<section class="text-gray-700 body-font overflow-hidden bg-white h-screen">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <img alt="ecommerce" class="lg:w-1/2 w-full object-cover object-center rounded border border-gray-200" src="{{plastic.image.url}}">
      <div class="lg:w-1/2 w-full lg:pl-10 lg:py-6 mt-6 lg:mt-0">
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-5">{{plastic.name}}</h1>
        
        <p class="leading-relaxed">{{plastic.description}}</p>
        <div class="flex mt-6 items-center pb-5 border-b-2 border-gray-200 mb-5">
          <div class="flex">
            <span class="mr-3">Seller</span>
              {{plastic.seller}}
          </div> 
        </div>
        <div class="flex">
          <span class="title-font font-medium text-2xl text-gray-900">&#8377 {{plastic.price}} /{{plastic.unit}}</span>
          {% if plastic.seller != user %}
          <a href="{% url 'chat:new' plastic.id %}" class="flex ml-auto text-white bg-primary border-0 py-2 px-6 focus:outline-none hover:bg-secondary rounded">
              Contact seller
          </a>
          {% else %}
          <a href="{% url 'shop:delete_plastic' plastic.id %}" class="flex ml-auto text-white bg-red-600 border-0 py-2 px-6 focus:outline-none hover:bg-red-700 rounded">
            Delete
          </a>
          <a href="{% url 'shop:update_plastic' plastic.id %}" class="flex ml-auto text-white bg-primary border-0 py-2 px-6 focus:outline-none hover:bg-secondary rounded">
            Update
          </a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

templates/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% load static tailwind_tags %}
{% block content %}
<section class="text-gray-700 body-font overflow-hidden bg-white h-screen">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <img alt="ecommerce" class="lg:w-1/2 w-full object-cover object-center rounded border border-gray-200" src="{{product.image.url}}">
      <div class="lg:w-1/2 w-full lg:pl-10 lg:py-6 mt-6 lg:mt-0">
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-5">{{product.name}}</h1>
        
        <p class="leading-relaxed">{{product.description}}</p>
        <div class="flex mt-6 items-center pb-5 border-b-2 border-gray-200 mb-5">
          <div class="flex">
            <span class="mr-3">Seller</span>
              {{product.seller}}
          </div> 
        </div>
        <div class="flex">
          <span class="title-font font-medium text-2xl text-gray-900">&#8377 {{product.price}}</span>
          {% if product.seller != user %}
          <a href="{% url 'cart:add_cart' product.id %}" class="flex ml-auto text-white bg-primary border-0 py-2 px-6 focus:outline-none hover:bg-secondary rounded">
              Add to cart
          </a>
          {% else %}
          <a href="{% url 'shop:delete_product' product.id %}" class="flex ml-auto text-white bg-red-600 border-0 py-2 px-6 focus:outline-none hover:bg-red-700 rounded">
            Delete
          </a>
          <a href="{% url 'shop:update_product' product.id %}" class="flex ml-auto text-white bg-primary border-0 py-2 px-6 focus:outline-none hover:bg-secondary rounded">
            Update
          </a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}